### PR TITLE
doc: Added allowed HTML in Markdown to readme

### PR DESCRIPTION
**Pull request by cb1kenobi**

### CODE REVIEW

**Comment by sallylanda6** [comment]
Since this info will apply to multiple repos and projects, I would like to find a way where this can be single sourced, otherwise we will have to maintain the content in multiple places. We also need to add this one <span style="white-space:nowrap">. We used it in the Configuration topic.

**Comment by cb1kenobi** [comment]
@sallylanda6 my concern is the information needs to be in a public place, not in a private wiki and the readme is an acceptable place to put such conventions. Perhaps this information should go in the contribution guidelines page?.

**Comment by sallylanda6** [comment]
I agree that it needs to be in a public repo and not in our internal wiki. But, it also needs to be written once and then reused across all projects. What about if we write it in the Axway-open-docs Readme and then each of our "microsite" doc projects includes a link to the info in that repo where the content is maintained?

**Comment by cb1kenobi** [comment]
That sounds like a great idea!

**Pull request closed without merging**
